cd 'D:\Data\olivia'

addpath('C:\Users\oakim\Documents\MATLAB',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\Analysis',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\Analysis\pressure test',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\Analysis\Ultilities',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\arduino',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\arduino\external\wmicget',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\shared',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\shared\analysis',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\shared\camera',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\shared\conditioning',...
    'C:\Users\oakim\Documents\MATLAB\neuroblinks_S723\shared\utilities')
    

gR
